# Generated by Django 5.0.4 on 2024-05-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=255)),
                ('CH2O', models.FloatField()),
                ('SCC', models.FloatField()),
                ('FAF', models.FloatField()),
                ('TUE', models.FloatField()),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('steps', models.IntegerField()),
                ('sleep_duration', models.FloatField()),
                ('sleep_quality', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('BMI', models.FloatField()),
                ('self_employed', models.IntegerField()),
                ('family_history_stress', models.IntegerField()),
                ('treatment', models.IntegerField()),
                ('days_Indoors', models.IntegerField()),
                ('growing_Stress', models.IntegerField()),
                ('changes_habits', models.IntegerField()),
                ('mental_health_history', models.IntegerField()),
                ('mood_swings', models.IntegerField()),
                ('coping_struggles', models.IntegerField()),
                ('work_interest', models.IntegerField()),
                ('social_weakness', models.IntegerField()),
                ('mental_health_interview', models.IntegerField()),
                ('care_options', models.IntegerField()),
                ('family_history_obese', models.IntegerField()),
                ('FAVC', models.IntegerField()),
                ('FCVC', models.FloatField()),
                ('NCP', models.FloatField()),
                ('sexe', models.IntegerField()),
                ('Occupation', models.IntegerField()),
                ('MTRANS', models.IntegerField()),
                ('CALC', models.IntegerField()),
                ('CAEF', models.IntegerField()),
            ],
        ),
    ]
