# Generated by Django 5.0.4 on 2024-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_annuel', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='physical_activity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stress_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
