# Generated by Django 5.0.4 on 2024-06-29 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_annuel', '0006_service_rename_user_user_user_followdatauser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followdatauser',
            name='caec',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followdatauser',
            name='calc',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followdatauser',
            name='ch2o',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followdatauser',
            name='faf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followdatauser',
            name='family_history_with_overweight',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='followdatauser',
            name='favc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followdatauser',
            name='fcvc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followdatauser',
            name='mtrans',
            field=models.CharField(blank=True, choices=[('Walking', 'Walking'), ('Bike', 'Bike'), ('Public_Transportation', 'Public_Transportation'), ('Automobile', 'Automobile')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followdatauser',
            name='ncp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followdatauser',
            name='scc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followdatauser',
            name='smoke',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followdatauser',
            name='tue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='caec',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='calc',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='ch2o',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='faf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='family_history_with_overweight',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='favc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='fcvc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='mtrans',
            field=models.CharField(blank=True, choices=[('Walking', 'Walking'), ('Bike', 'Bike'), ('Public_Transportation', 'Public_Transportation'), ('Automobile', 'Automobile')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='ncp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='physical_activity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='scc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='smoke',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='stress_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='tue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='caec',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='calc',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ch2o',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='faf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_history_with_overweight',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fcvc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mtrans',
            field=models.CharField(blank=True, choices=[('Walking', 'Walking'), ('Bike', 'Bike'), ('Public_Transportation', 'Public_Transportation'), ('Automobile', 'Automobile')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ncp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smoke',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ObesityPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
