# Generated by Django 5.0.4 on 2024-06-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet_annuel', '0007_followdatauser_caec_followdatauser_calc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_user',
            name='physical_activity',
        ),
        migrations.RemoveField(
            model_name='user_user',
            name='stress_level',
        ),
    ]
