# Generated by Django 5.0.4 on 2024-06-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_annuel', '0008_remove_user_user_physical_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_user',
            name='physical_activity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_user',
            name='stress_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
