# Generated by Django 5.0.4 on 2024-06-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_annuel', '0009_user_user_physical_activity_user_user_stress_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followdatauser',
            name='caec',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='followdatauser',
            name='calc',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='followdatauser',
            name='favc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='followdatauser',
            name='mtrans',
            field=models.CharField(blank=True, choices=[('Walking', 'Walking'), ('Bike', 'Bike'), ('Public_Transportation', 'Public_Transportation'), ('Automobile', 'Automobile')], max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='followdatauser',
            name='scc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='followdatauser',
            name='smoke',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user_user',
            name='caec',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_user',
            name='calc',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_user',
            name='favc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user_user',
            name='mtrans',
            field=models.CharField(blank=True, choices=[('Walking', 'Walking'), ('Bike', 'Bike'), ('Public_Transportation', 'Public_Transportation'), ('Automobile', 'Automobile')], max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='user_user',
            name='scc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user_user',
            name='smoke',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='caec',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='calc',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mtrans',
            field=models.CharField(blank=True, choices=[('Walking', 'Walking'), ('Bike', 'Bike'), ('Public_Transportation', 'Public_Transportation'), ('Automobile', 'Automobile')], max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smoke',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
