# Generated by Django 5.0.4 on 2024-06-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet_annuel', '0010_alter_followdatauser_caec_alter_followdatauser_calc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObesityPrediction',
        ),
    ]
